/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Users', [{
      firstName: 'Лиза',
      lastName: 'Солодовник',
      email: 'user1@1',
      password: '$2b$10$awU/uAPvCVU9OABxMRWrZuYWyu9eoVNoofMua28aDBhFLkrhRdxCS',
      avatar: 'liza.jpeg',
      role: 'owner',
      gender: 'Женщина',
      phone: '+79123456679',
      info: 'Кот в наличии. Немного сволочь, но красивый. Будит в 5 утра, но за красивые глаза простительно. Нужно сбагрить в хорошие руки до понедельника.',
      location: 'Москва',
      status: 'Есть опыт',
      websites: 'https://t.me/chiprussia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: 'Ксения',
      lastName: 'Паршикова',
      email: 'user2@2',
      password: '$2b$10$awU/uAPvCVU9OABxMRWrZuYWyu9eoVNoofMua28aDBhFLkrhRdxCS',
      avatar: 'ksenia.jpeg',
      role: 'hunter',
      gender: 'Женщина',
      phone: '12345667',
      info: 'Не фанатка семьи Калленых и кошачих.',
      location: 'Москва',
      status: 'Есть опыт',
      websites: 'https://t.me/chiprussia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: 'Даниил',
      lastName: 'Мартаков',
      email: 'user3@3',
      password: '$2b$10$awU/uAPvCVU9OABxMRWrZuYWyu9eoVNoofMua28aDBhFLkrhRdxCS',
      avatar: 'daniil.jpeg',
      role: 'hunter',
      gender: 'Мужчина',
      phone: '12345667',
      info: 'Опыта нет, но опыт будет. Люблю котиков. Своего нет, но присмотрю за вашим.',
      location: 'Москва',
      status: 'Отсутствует',
      websites: 'https://t.me/chiprussia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: 'Шамиль',
      lastName: 'Газалапов',
      email: 'user4@4',
      password: '$2b$10$awU/uAPvCVU9OABxMRWrZuYWyu9eoVNoofMua28aDBhFLkrhRdxCS',
      avatar: 'shamil.jpeg',
      role: 'owner',
      gender: 'Мужчина',
      phone: '12345667',
      info: 'В стае развелось слишком много ртов. Продам волка за ненадобностью.',
      location: 'Москва',
      status: 'Есть опыт',
      websites: 'https://t.me/chiprussia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: 'Петр',
      lastName: 'Петров',
      email: '1@1',
      password: '$2b$10$awU/uAPvCVU9OABxMRWrZuYWyu9eoVNoofMua28aDBhFLkrhRdxCS',
      avatar: 'petr.webp',
      role: 'hunter',
      gender: 'Мужчина',
      phone: '12345667',
      info: 'Ищу кота по интересам',
      location: 'Москва',
      status: 'Есть опыт',
      websites: 'https://t.me/chiprussia',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      firstName: 'Василий',
      lastName: 'Васильев',
      email: '1@11',
      password: '$2b$10$awU/uAPvCVU9OABxMRWrZuYWyu9eoVNoofMua28aDBhFLkrhRdxCS',
      avatar: '1668668114555--JxiE.gif',
      role: 'hunter',
      gender: 'Мужчина',
      phone: '98765432',
      info: 'Недавно обнаружил, что ведро есть, а кота нет...',
      location: 'Сочи',
      status: 'Отсутствует',
      websites: 'https://t.me/chiprussia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: 'Николай',
      lastName: 'Николаев',
      email: '2@2',
      password: '$2b$10$awU/uAPvCVU9OABxMRWrZuYWyu9eoVNoofMua28aDBhFLkrhRdxCS',
      avatar: 'man3.jpg',
      role: 'owner',
      gender: 'Мужчина',
      phone: '45678',
      info: 'Устал от жизни с котом.',
      location: 'Екатеринбург',
      status: 'Есть опыт',
      websites: 'https://t.me/chiprussia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: 'Мария',
      lastName: 'Марьянова',
      email: '2@22',
      password: '$2b$10$awU/uAPvCVU9OABxMRWrZuYWyu9eoVNoofMua28aDBhFLkrhRdxCS',
      avatar: 'woman1.jpg',
      role: 'owner',
      gender: 'Женщина',
      phone: '000000000',
      info: 'Закончились попытки заработать на кошках',
      location: 'Москва',
      status: 'Есть опыт',
      websites: 'https://t.me/chiprussia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: 'Екатерина',
      lastName: 'Екатеринова',
      email: '2@222',
      password: '$2b$10$awU/uAPvCVU9OABxMRWrZuYWyu9eoVNoofMua28aDBhFLkrhRdxCS',
      avatar: 'woman2.jpg',
      role: 'owner',
      gender: 'Женщина',
      phone: '12345667',
      info: 'Продам волка за ненадобностью.',
      location: 'Москва',
      status: 'Есть опыт',
      websites: 'https://t.me/chiprussia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      firstName: 'Эдвард',
      lastName: ' ',
      email: 'ed@1',
      password: '$2b$10$awU/uAPvCVU9OABxMRWrZuYWyu9eoVNoofMua28aDBhFLkrhRdxCS',
      avatar: 'edvard.jpeg',
      role: 'hunter',
      gender: 'Мужчина',
      phone: '6666666666',
      info: '',
      location: 'Москва',
      status: 'Есть опыт',
      websites: 'https://t.me/chiprussia',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      firstName: 'Никита',
      lastName: ' ',
      email: 'nikita@1',
      password: '$2b$10$awU/uAPvCVU9OABxMRWrZuYWyu9eoVNoofMua28aDBhFLkrhRdxCS',
      avatar: 'nik.jpg',
      role: 'hunter',
      gender: 'Мужчина',
      phone: '6666666666',
      info: 'Ищу оборотня для дальнейших действий...',
      location: 'Москва',
      status: 'Есть опыт',
      websites: 'https://t.me/chiprussia',
      createdAt: new Date(),
      updatedAt: new Date(),
    }], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
