/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Animals', [{
      name: 'Жоррра',
      animal_type: 'cats',
      breed: 'Мейн-кун',
      color: 'Черный',
      age: 'Взрослый',
      med_info: 'Вместе со мной переболел короновирусом',
      about: 'Жирный',
      images: JSON.stringify(['cat1.jpeg', 'cat2.jpg', 'cat3.jpg']),
      price_category: 'Платно',
      price: '10 копеек',
      period_category: 'Забрать',
      period: '',
      gender: 'Мальчик',
      userId: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Ники',
      animal_type: 'cats',
      breed: 'Сибирская',
      color: 'Белый',
      age: 'Взрослый',
      med_info: 'Однажды случайно упала в святую воду',
      about: 'Не чё так',
      images: JSON.stringify(['cat4.jpg', 'cat5.jpg', 'cat6.jpg']),
      price_category: 'Платно',
      price: '100 рублей',
      period_category: 'Забрать',
      period: '',
      gender: 'Девочка',
      userId: 7,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Плотва',
      animal_type: 'wolves',
      breed: 'Арктический',
      color: 'Серый',
      age: 'Взрослый',
      med_info: 'Лечился в лесу',
      about: 'Кусается больно',
      images: JSON.stringify(['volk1.jpg', 'volk2.jpg']),
      price_category: 'Платно',
      price: '0 рублей',
      period_category: 'Забрать',
      period: '',
      gender: 'Мальчик',
      userId: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Мага',
      animal_type: 'wolves',
      breed: 'Кавказский',
      color: 'Серый',
      age: 'Взрослый',
      med_info: 'Сожрал всю аптечку',
      about: "Откликается на 'Эй' ",
      images: JSON.stringify(['volk3.jpg', 'volk4.jpg']),
      price_category: 'Бесплатно',
      price: '',
      period_category: 'На передержку',
      period: '3 дня',
      gender: 'Девочка',
      userId: 8,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Инна',
      animal_type: 'foxes',
      breed: '',
      color: 'Рыжий',
      age: 'Взрослый',
      med_info: 'Здоровый, вроде',
      about: 'Много жрёт тварь',
      images: JSON.stringify(['lisa1.jpg', 'lisa2.jpg', 'lisa3.jpg', 'lisa4.jpeg']),
      price_category: 'Бесплатно',
      price: '',
      period_category: 'На передержку',
      period: '7 недель',
      gender: 'Девочка',
      userId: 7,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Толик',
      animal_type: 'dogs',
      breed: '',
      color: '',
      age: 'Взрослый',
      med_info: 'Серый',
      about: '',
      images: JSON.stringify(['dog1.jpeg', 'dog2.jpg', 'dog3.jpg', 'dog4.jpg']),
      price_category: 'Платно',
      price: '789 коппек',
      period_category: 'Забрать',
      period: '',
      gender: 'Мальчик',
      userId: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Просто волк',
      animal_type: 'wolves',
      breed: 'Сибирский лесной',
      color: 'Белый',
      age: 'Взрослый',
      med_info: '',
      about: '',
      images: JSON.stringify(['volk5.jpg', 'volk6.jpeg', 'volk7.jpg']),
      price_category: 'Платно',
      price: '1 литр горючего вещества',
      period_category: 'Забрать',
      period: '',
      gender: 'Девочка',
      userId: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Иннокентий',
      animal_type: 'racoons',
      breed: '',
      color: 'Серый',
      age: 'Взрослый',
      med_info: '',
      about: '',
      images: JSON.stringify(['racoon1.jpg', 'racoon2.jpg', 'racoon3.jpg', 'racoon4.jpg', 'racoon5.jpg']),
      price_category: 'Платно',
      price: '100 рублей',
      period_category: 'Забрать',
      period: '',
      gender: 'Мальчик',
      userId: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Просто лиса',
      animal_type: 'foxes',
      breed: '',
      color: 'Рыжий',
      age: 'Взрослый',
      med_info: '',
      about: '',
      images: JSON.stringify(['lisa5.jpg', 'lisa6.jpg', 'lisa7.jpg']),
      price_category: 'Бесплатно',
      price: '',
      period_category: 'На передержку',
      period: '7 дней и ночей',
      gender: 'Девочка',
      userId: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Деймон',
      animal_type: 'cats',
      breed: 'Шотландская вислоухая',
      color: 'Черный',
      age: 'Взрослый',
      med_info: 'Однажды случайно упала в святую воду',
      about: 'Не чё так',
      images: JSON.stringify(['damon1.jpg', 'damon2.jpg', 'damon3.jpg', 'damon4.jpg', 'damon5.jpg']),
      price_category: 'Бесплатно',
      price: '',
      period_category: 'На передержку',
      period: 'На выходные',
      gender: 'Мальчик',
      userId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Джейкоб',
      animal_type: 'wolves',
      breed: 'Арктический',
      color: 'Рыжий',
      age: 'Взрослый',
      med_info: 'Привит и вакцинирован',
      about: 'Горячий парень. Не кусается (ну только если попросить)',
      images: JSON.stringify(['werewolf1.jpg', 'werewolf2.jpg', 'werewolf3.jpg', 'werewolf4.jpg']),
      price_category: 'Бесплатно',
      price: '',
      period_category: 'Забрать',
      period: '',
      gender: 'Мальчик',
      userId: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Сэм',
      animal_type: 'wolves',
      breed: 'Арктический',
      color: 'Черный',
      age: 'Взрослый',
      med_info: 'Привит и вакцинирован',
      about: 'Рос почти примерным парнем. Большой, как лошадь. Любит вкусно покушать. Немного агрессивный.',
      images: JSON.stringify(['sam1.jpg', 'sam2.jpeg']),
      price_category: 'Бесплатно',
      price: '',
      period_category: 'Забрать',
      period: '',
      gender: 'Мальчик',
      userId: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Сэт',
      animal_type: 'wolves',
      breed: 'Арктический',
      color: 'Серый',
      age: 'Взрослый',
      med_info: 'Привит и вакцинирован',
      about: 'Дружелюбный парень. Высокий и крупный, с большими лапами и мехом песочного цвета.',
      images: JSON.stringify(['set1.webp', 'set3.jpeg', 'set2.jpeg']),
      price_category: 'Бесплатно',
      price: '',
      period_category: 'Забрать',
      period: '',
      gender: 'Мальчик',
      userId: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Animals', null, {});
  },
};
